//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionSeguridad.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguridadMejorada2Entities : DbContext
    {
        public SeguridadMejorada2Entities()
            : base("name=SeguridadMejorada2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditoriaCambios> AuditoriaCambios { get; set; }
        public virtual DbSet<HistorialUsuarios> HistorialUsuarios { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<Permisos_Menus> Permisos_Menus { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
